// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoronResuelve.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoronResuelve.Api.Migrations
{
    [DbContext(typeof(MoronResuelveContext))]
    [Migration("20260925010905_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoronResuelve.Api.Models.CategoriaIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaseBadgeColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaseContenedorIcono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoCategoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IconoRelleno")
                        .HasColumnType("boolean");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("CategoriasIncidencias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "vialidad",
                            ClaseBadgeColor = "bg-secondary-container text-on-secondary-fixed",
                            ClaseContenedorIcono = "bg-surface-container text-primary",
                            CodigoCategoria = "01",
                            Descripcion = "Pavimento hundido, pozos y fisuras vehiculares.",
                            Icono = "traffic_jam",
                            IconoRelleno = false,
                            Numero = "01",
                            Sla = "48-72h",
                            Slug = "baches-calles",
                            Titulo = "Baches en calles"
                        },
                        new
                        {
                            Id = 2,
                            Area = "alumbrado",
                            ClaseBadgeColor = "bg-tertiary-fixed-dim/40 text-on-tertiary-fixed",
                            ClaseContenedorIcono = "bg-tertiary-fixed text-tertiary-container",
                            CodigoCategoria = "02",
                            Descripcion = "Farolas intermitentes, sin luz o tulipas rotas.",
                            Icono = "lightbulb",
                            IconoRelleno = false,
                            Numero = "02",
                            Sla = "24-48h",
                            Slug = "alumbrado-apagado",
                            Titulo = "Alumbrado apagado"
                        },
                        new
                        {
                            Id = 3,
                            Area = "vialidad",
                            ClaseBadgeColor = "bg-error-container text-on-error-container",
                            ClaseContenedorIcono = "bg-primary-fixed text-primary",
                            CodigoCategoria = "03",
                            Descripcion = "Apagados, titilantes o desincronizados.",
                            Icono = "traffic",
                            IconoRelleno = false,
                            Numero = "03",
                            Sla = "Urgente 6h",
                            Slug = "semaforos-fallas",
                            Titulo = "Semáforos"
                        },
                        new
                        {
                            Id = 4,
                            Area = "higiene",
                            ClaseBadgeColor = "bg-secondary-container text-on-secondary-fixed",
                            ClaseContenedorIcono = "bg-surface-container text-secondary",
                            CodigoCategoria = "04",
                            Descripcion = "Microbasurales, residuos fuera de horario.",
                            Icono = "delete",
                            IconoRelleno = false,
                            Numero = "04",
                            Sla = "24h",
                            Slug = "acumulacion-basura",
                            Titulo = "Acumulación basura"
                        },
                        new
                        {
                            Id = 5,
                            Area = "vialidad",
                            ClaseBadgeColor = "bg-secondary-container text-on-secondary-fixed",
                            ClaseContenedorIcono = "bg-secondary-fixed text-primary",
                            CodigoCategoria = "05",
                            Descripcion = "Caños rotos en vereda o calzada pública.",
                            Icono = "water_damage",
                            IconoRelleno = false,
                            Numero = "05",
                            Sla = "24-48h",
                            Slug = "perdidas-agua",
                            Titulo = "Pérdidas de agua"
                        },
                        new
                        {
                            Id = 6,
                            Area = "espacios",
                            ClaseBadgeColor = "bg-error-container text-on-error-container",
                            ClaseContenedorIcono = "bg-tertiary-fixed text-tertiary",
                            CodigoCategoria = "06",
                            Descripcion = "Ramas quebradas, troncos o raíces descalzadas.",
                            Icono = "nature_people",
                            IconoRelleno = false,
                            Numero = "06",
                            Sla = "Prioridad",
                            Slug = "arboles-riesgo",
                            Titulo = "Árboles caídos/riesgo"
                        },
                        new
                        {
                            Id = 7,
                            Area = "vialidad",
                            ClaseBadgeColor = "bg-secondary-container text-on-secondary-fixed",
                            ClaseContenedorIcono = "bg-surface-container text-secondary",
                            CodigoCategoria = "07",
                            Descripcion = "Baldosas levantadas, cordones destruidos.",
                            Icono = "broken_image",
                            IconoRelleno = false,
                            Numero = "07",
                            Sla = "Programable",
                            Slug = "veredas-rotas",
                            Titulo = "Calles o veredas"
                        },
                        new
                        {
                            Id = 8,
                            Area = "vialidad",
                            ClaseBadgeColor = "bg-secondary-container text-on-secondary-fixed",
                            ClaseContenedorIcono = "bg-primary-fixed text-primary",
                            CodigoCategoria = "08",
                            Descripcion = "Carteles doblados, caídos o ilegibles.",
                            Icono = "signpost",
                            IconoRelleno = false,
                            Numero = "08",
                            Sla = "48h",
                            Slug = "senales-transito",
                            Titulo = "Señales de tránsito"
                        },
                        new
                        {
                            Id = 9,
                            Area = "vialidad",
                            ClaseBadgeColor = "bg-secondary-container text-on-secondary-fixed",
                            ClaseContenedorIcono = "bg-secondary-fixed text-secondary",
                            CodigoCategoria = "09",
                            Descripcion = "Refugios rotos, vidrios estallados, sin asiento.",
                            Icono = "departure_board",
                            IconoRelleno = false,
                            Numero = "09",
                            Sla = "72h",
                            Slug = "paradas-colectivo",
                            Titulo = "Paradas de colectivo"
                        },
                        new
                        {
                            Id = 10,
                            Area = "higiene",
                            ClaseBadgeColor = "bg-secondary-container text-on-secondary-fixed",
                            ClaseContenedorIcono = "bg-surface-container text-secondary",
                            CodigoCategoria = "10",
                            Descripcion = "Frentes públicos o monumentos vandalizados.",
                            Icono = "format_paint",
                            IconoRelleno = false,
                            Numero = "10",
                            Sla = "Cuadrilla",
                            Slug = "graffitis",
                            Titulo = "Pintadas / Graffitis"
                        },
                        new
                        {
                            Id = 11,
                            Area = "seguridad",
                            ClaseBadgeColor = "bg-secondary-container text-on-secondary-fixed",
                            ClaseContenedorIcono = "bg-surface-container text-primary",
                            CodigoCategoria = "11",
                            Descripcion = "Carrocerías quemadas, sin ruedas o en desuso.",
                            Icono = "car_crash",
                            IconoRelleno = false,
                            Numero = "11",
                            Sla = "Inspección",
                            Slug = "vehiculos-abandonados",
                            Titulo = "Autos abandonados"
                        },
                        new
                        {
                            Id = 12,
                            Area = "seguridad",
                            ClaseBadgeColor = "bg-tertiary-fixed-dim/50 text-on-tertiary-fixed",
                            ClaseContenedorIcono = "bg-tertiary-fixed text-tertiary",
                            CodigoCategoria = "12",
                            Descripcion = "Mascotas heridas, extraviadas o en riesgo.",
                            Icono = "pets",
                            IconoRelleno = false,
                            Numero = "12",
                            Sla = "Zoonosis",
                            Slug = "animales-abandonados",
                            Titulo = "Fauna Urbana / Zoonosis"
                        },
                        new
                        {
                            Id = 13,
                            Area = "vialidad",
                            ClaseBadgeColor = "bg-error-container text-on-error-container",
                            ClaseContenedorIcono = "bg-secondary-fixed text-primary",
                            CodigoCategoria = "13",
                            Descripcion = "Bocas de tormenta tapadas, agua estancada.",
                            Icono = "tsunami",
                            IconoRelleno = false,
                            Numero = "13",
                            Sla = "Alerta 12h",
                            Slug = "sumideros-inundaciones",
                            Titulo = "Sumideros e Inundación"
                        },
                        new
                        {
                            Id = 14,
                            Area = "seguridad",
                            ClaseBadgeColor = "bg-secondary-container text-on-secondary-fixed",
                            ClaseContenedorIcono = "bg-surface-container text-secondary",
                            CodigoCategoria = "14",
                            Descripcion = "Música a alto volumen reiterada, obras ilegales.",
                            Icono = "volume_up",
                            IconoRelleno = false,
                            Numero = "14",
                            Sla = "Inspección",
                            Slug = "ruidos-molestos",
                            Titulo = "Ruidos molestos"
                        },
                        new
                        {
                            Id = 15,
                            Area = "seguridad",
                            ClaseBadgeColor = "bg-error-container text-on-error-container",
                            ClaseContenedorIcono = "bg-primary-fixed text-primary",
                            CodigoCategoria = "15",
                            Descripcion = "Mampostería con desprendimiento, derrumbe.",
                            Icono = "domain",
                            IconoRelleno = false,
                            Numero = "15",
                            Sla = "Obras",
                            Slug = "estructuras-peligro",
                            Titulo = "Estructuras en riesgo"
                        },
                        new
                        {
                            Id = 16,
                            Area = "vialidad",
                            ClaseBadgeColor = "bg-secondary-container text-on-secondary-fixed",
                            ClaseContenedorIcono = "bg-secondary-fixed text-secondary",
                            CodigoCategoria = "16",
                            Descripcion = "Separadores rotos, pintura borrada u ocupadas.",
                            Icono = "pedal_bike",
                            IconoRelleno = false,
                            Numero = "16",
                            Sla = "48h",
                            Slug = "bicisendas",
                            Titulo = "Bicisendas"
                        },
                        new
                        {
                            Id = 17,
                            Area = "espacios",
                            ClaseBadgeColor = "bg-secondary-container text-on-secondary-fixed",
                            ClaseContenedorIcono = "bg-surface-container text-secondary",
                            CodigoCategoria = "17",
                            Descripcion = "Pasto crecido, hamacas rotas o bancos dañados.",
                            Icono = "park",
                            IconoRelleno = false,
                            Numero = "17",
                            Sla = "3 a 5 días",
                            Slug = "espacios-verdes",
                            Titulo = "Plazas y juegos"
                        },
                        new
                        {
                            Id = 18,
                            Area = "higiene",
                            ClaseBadgeColor = "bg-secondary-container text-on-secondary-fixed",
                            ClaseContenedorIcono = "bg-primary-fixed text-primary",
                            CodigoCategoria = "18",
                            Descripcion = "Quemados, sin tapa, ruedas rotas o volcados.",
                            Icono = "local_fire_department",
                            IconoRelleno = false,
                            Numero = "18",
                            Sla = "Reemplazo 24h",
                            Slug = "contenedores-danados",
                            Titulo = "Contenedores rotos"
                        },
                        new
                        {
                            Id = 19,
                            Area = "seguridad",
                            ClaseBadgeColor = "bg-secondary-container text-on-secondary-fixed",
                            ClaseContenedorIcono = "bg-surface-container text-secondary",
                            CodigoCategoria = "19",
                            Descripcion = "Montículos de escombros, veredas bloqueadas.",
                            Icono = "crop_free",
                            IconoRelleno = false,
                            Numero = "19",
                            Sla = "48h",
                            Slug = "obstaculos-paso",
                            Titulo = "Obstáculos en paso"
                        },
                        new
                        {
                            Id = 20,
                            Area = "alumbrado",
                            ClaseBadgeColor = "bg-error text-on-error",
                            ClaseContenedorIcono = "bg-error-container text-on-error-container",
                            CodigoCategoria = "20",
                            Descripcion = "Cables colgando, chispas o postes inclinados.",
                            Icono = "bolt",
                            IconoRelleno = true,
                            Numero = "20",
                            Sla = "Urgente",
                            Slug = "cables-peligro-electrico",
                            Titulo = "Cables o postes"
                        });
                });

            modelBuilder.Entity("MoronResuelve.Api.Models.ImagenIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IncidenciaId");

                    b.ToTable("ImagenesIncidencias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IncidenciaId = 1,
                            Url = "https://lh3.googleusercontent.com/aida-public/AB6AXuBwkOFk8IIK50La8Np0y9fRuSNIp2aDqwaBzNXgFBmT48hSSznS8OcrsqQO9BVjDKyj8KNdhnyOdxHiIG79nERkBnAeTI0PpxNOHjLZpHUA2DpV_lT3kNhCd-hFi6xXYwQZuPVH_GafKjEWbDeeA0IWvWqU4QdnOJe986wOi0WyN3zjImtUSMdkHKKmF5hDtiChLSQ5K4pI7-w2RWPIheovz-MokNbuidVw7HMYuMu-eSlK_AVHoofC"
                        },
                        new
                        {
                            Id = 2,
                            IncidenciaId = 2,
                            Url = "https://lh3.googleusercontent.com/aida-public/AB6AXuDJNqRtdOqE16Kt_RJ_wvKQD6E0e8UEXEF_irHJdSUxMBZIPgBQT-rEu80EblXc6CmmyaVMb3cbmkxNfcybIj1WiR7dA8rD-5WD0LaiLlNG4ImnyxdlxYxiOlytKbXbMurzBXTRhuxOGm2IXBoqi5pZNr7OCXAPv0pE1-CPZoyO9Hmze3HVJ8gIKb0HaG6i6bjRPXHnumEsa0SIBoHMbH9M-jJlIGziiRvJraUeWkIxlKLVrj4i5lYD"
                        },
                        new
                        {
                            Id = 3,
                            IncidenciaId = 3,
                            Url = "https://lh3.googleusercontent.com/aida-public/AB6AXuDFcV463bufaR4g22dd3KNdwMzFbSXzo2ecpxNdcxBwKmdnyGJeuc-iKAMG4lBLPPyp1VXwBHsNsphRQ2tdlOgVco6CuY8QxhUp_wUi5glwvsAGVpmYel9-5Iyt6cZWERNZtkKLHFIsF90lb2vwBYFiotExRpa51MIKhfFH12RFtUTBk9Gr_uNvhfkGpAHavj2ikhn2KwUbJqhajFVWMRIehuYL3EJk7eoW_4lNJpHuacqtNC0IoSiU"
                        });
                });

            modelBuilder.Entity("MoronResuelve.Api.Models.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Area")
                        .HasColumnType("integer");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoriaSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CuadrillaAsignada")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailReportante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotasInspector")
                        .HasColumnType("text");

                    b.Property<string>("OperadorACargo")
                        .HasColumnType("text");

                    b.Property<string>("ReportadoPor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonoReportante")
                        .HasColumnType("text");

                    b.Property<string>("TiempoTranscurrido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Urgencia")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Incidencias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 0,
                            Categoria = "Bacheo y Asfalto",
                            CategoriaSlug = "baches-calles",
                            Codigo = "MOR-4821",
                            CuadrillaAsignada = "Obras Públicas / Bacheo Móvil #4",
                            Descripcion = "Bache de gran profundidad obstruyendo carril derecho hacia estación Morón. Peligro para transporte público.",
                            EmailReportante = "al_garcia@eest6.edu.ar",
                            Estado = 0,
                            FechaCreacion = new DateTime(2025, 10, 14, 13, 14, 0, 0, DateTimeKind.Utc),
                            Localidad = "Morón Centro",
                            NotasInspector = "Bache de gran profundidad que genera peligro para el paso del transporte público sobre carril derecho.",
                            ReportadoPor = "Juan García",
                            TiempoTranscurrido = "Hace 28 min",
                            Titulo = "Baches profundos en calzada",
                            Ubicacion = "Av. Rivadavia 17400, Morón Centro",
                            Urgencia = 2,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Area = 1,
                            Categoria = "Alumbrado y Electromecánica",
                            CategoriaSlug = "alumbrado-apagado",
                            Codigo = "MOR-4819",
                            CuadrillaAsignada = "Alumbrado y Electromecánica",
                            Descripcion = "Sector juegos infantiles y sendero principal a oscuras desde la tormenta del martes. Requiere grúa de altura.",
                            EmailReportante = "m.rossi@gmail.com",
                            Estado = 0,
                            FechaCreacion = new DateTime(2025, 10, 14, 11, 30, 0, 0, DateTimeKind.Utc),
                            Localidad = "Castelar Sur",
                            NotasInspector = "Sector juegos infantiles y sendero a oscuras. Requiere grúa con cesta hidráulica.",
                            ReportadoPor = "Mariana Rossi",
                            TiempoTranscurrido = "Hace 2 hs",
                            Titulo = "Alumbrado público apagado",
                            Ubicacion = "Plaza San Martín, Castelar",
                            Urgencia = 1
                        },
                        new
                        {
                            Id = 3,
                            Area = 2,
                            Categoria = "Higiene Urbana",
                            CategoriaSlug = "acumulacion-basura",
                            Codigo = "MOR-4815",
                            CuadrillaAsignada = "Higiene Urbana - Móvil 12",
                            Descripcion = "Recolectando restos de poda y escombros ilegales. Camión recolector compactador asignado.",
                            EmailReportante = "carlos.d@moron.gob.ar",
                            Estado = 1,
                            FechaCreacion = new DateTime(2025, 10, 14, 10, 45, 0, 0, DateTimeKind.Utc),
                            Localidad = "Morón Sur",
                            NotasInspector = "Ramas acumuladas bloqueando rampa de discapacitados y vereda.",
                            OperadorACargo = "M. Benítez",
                            ReportadoPor = "Carlos Domínguez",
                            TiempoTranscurrido = "Hace 4 hs",
                            Titulo = "Microbasural / Ramas acumuladas",
                            Ubicacion = "Casullo y Brown, Morón Sur",
                            Urgencia = 1
                        },
                        new
                        {
                            Id = 4,
                            Area = 1,
                            Categoria = "Alumbrado Público",
                            CategoriaSlug = "alumbrado-apagado",
                            Codigo = "MOR-4519",
                            CuadrillaAsignada = "Alumbrado #2",
                            Descripcion = "Lámpara LED titilando y apagada sobre calle vecinal.",
                            EmailReportante = "al_garcia@eest6.edu.ar",
                            Estado = 2,
                            FechaCreacion = new DateTime(2025, 10, 13, 13, 0, 0, 0, DateTimeKind.Utc),
                            Localidad = "Castelar Norte",
                            ReportadoPor = "Juan García",
                            TiempoTranscurrido = "Solucionado ayer",
                            Titulo = "Luminaria LED quemada",
                            Ubicacion = "Carlos Casares 840, Castelar",
                            Urgencia = 0,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 5,
                            Area = 3,
                            Categoria = "Higiene Urbana",
                            CategoriaSlug = "arboles-riesgo",
                            Codigo = "MOR-4301",
                            CuadrillaAsignada = "Espacios Verdes",
                            Descripcion = "Gran cantidad de ramas tras tormenta.",
                            EmailReportante = "al_garcia@eest6.edu.ar",
                            Estado = 2,
                            FechaCreacion = new DateTime(2025, 10, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Localidad = "Morón Centro",
                            ReportadoPor = "Juan García",
                            TiempoTranscurrido = "Solucionado 12 Oct",
                            Titulo = "Restos de poda acumulados",
                            Ubicacion = "San Martín 310, Morón Centro",
                            Urgencia = 0,
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("MoronResuelve.Api.Models.LineaTiempo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DespachadoEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("integer");

                    b.Property<int>("PasoActual")
                        .HasColumnType("integer");

                    b.Property<string>("RecibidoEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResolucionEstimada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RevisadoEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IncidenciaId")
                        .IsUnique();

                    b.ToTable("LineasTiempo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DespachadoEn = "En viaje",
                            IncidenciaId = 1,
                            PasoActual = 3,
                            RecibidoEn = "10:14 hs",
                            ResolucionEstimada = "Estimado 17:00 hs",
                            RevisadoEn = "11:05 hs"
                        },
                        new
                        {
                            Id = 2,
                            DespachadoEn = "Pendiente",
                            IncidenciaId = 2,
                            PasoActual = 2,
                            RecibidoEn = "08:30 hs",
                            ResolucionEstimada = "Estimado mañana 12:00 hs",
                            RevisadoEn = "09:15 hs"
                        },
                        new
                        {
                            Id = 3,
                            DespachadoEn = "09:00 hs",
                            IncidenciaId = 3,
                            PasoActual = 3,
                            RecibidoEn = "07:45 hs",
                            ResolucionEstimada = "Estimado 13:00 hs",
                            RevisadoEn = "08:10 hs"
                        },
                        new
                        {
                            Id = 4,
                            DespachadoEn = "Ayer 14:00 hs",
                            IncidenciaId = 4,
                            PasoActual = 4,
                            RecibidoEn = "Ayer 10:00 hs",
                            ResolucionEstimada = "Resuelto ayer 18:30 hs",
                            RevisadoEn = "Ayer 11:00 hs"
                        },
                        new
                        {
                            Id = 5,
                            DespachadoEn = "12 Oct 13:00 hs",
                            IncidenciaId = 5,
                            PasoActual = 4,
                            RecibidoEn = "12 Oct 09:00 hs",
                            ResolucionEstimada = "Resuelto 12 Oct 16:45 hs",
                            RevisadoEn = "12 Oct 10:30 hs"
                        });
                });

            modelBuilder.Entity("MoronResuelve.Api.Models.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlugId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SlugId")
                        .IsUnique();

                    b.ToTable("Localidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Morón Centro (UGC 1)",
                            SlugId = "moron-centro"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Haedo (UGC 2)",
                            SlugId = "haedo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "El Palomar (UGC 3)",
                            SlugId = "el-palomar"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Castelar Norte (UGC 4)",
                            SlugId = "castelar-norte"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Castelar Sur (UGC 5)",
                            SlugId = "castelar-sur"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Morón Sur (UGC 6)",
                            SlugId = "moron-sur"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Villa Sarmiento (UGC 7)",
                            SlugId = "villa-sarmiento"
                        });
                });

            modelBuilder.Entity("MoronResuelve.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaVerificado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "al_garcia@eest6.edu.ar",
                            EstaVerificado = true,
                            FechaRegistro = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Localidad = "Castelar Sur",
                            Nivel = 3,
                            Nombre = "Juan García",
                            PasswordHash = "$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
                            Puntos = 850,
                            Rol = 0,
                            Telefono = "11-2345-6789"
                        });
                });

            modelBuilder.Entity("MoronResuelve.Api.Models.ImagenIncidencia", b =>
                {
                    b.HasOne("MoronResuelve.Api.Models.Incidencia", "Incidencia")
                        .WithMany("Imagenes")
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incidencia");
                });

            modelBuilder.Entity("MoronResuelve.Api.Models.Incidencia", b =>
                {
                    b.HasOne("MoronResuelve.Api.Models.Usuario", "Usuario")
                        .WithMany("Incidencias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MoronResuelve.Api.Models.LineaTiempo", b =>
                {
                    b.HasOne("MoronResuelve.Api.Models.Incidencia", "Incidencia")
                        .WithOne("LineaTiempo")
                        .HasForeignKey("MoronResuelve.Api.Models.LineaTiempo", "IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incidencia");
                });

            modelBuilder.Entity("MoronResuelve.Api.Models.Incidencia", b =>
                {
                    b.Navigation("Imagenes");

                    b.Navigation("LineaTiempo");
                });

            modelBuilder.Entity("MoronResuelve.Api.Models.Usuario", b =>
                {
                    b.Navigation("Incidencias");
                });
#pragma warning restore 612, 618
        }
    }
}
